name: blog-recommender-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- Conda Packages ---
  - python=3.11
  - pandas
  - numpy<2.0
  - scikit-learn
  - matplotlib
  - seaborn
  - wordcloud
  - jupyter
  - nltk
  - pytorch
  - cpuonly
  - sentence-transformers
  - implicit
  - umap-learn
  - black
  - isort
  - flake8
  - pylint
  - pip
  - h5py
  - scikit-surprise

  # --- Pip Packages ---
  - pip:
    - streamlit
    - openai
    - python-dotenv
    - tqdm
    - transformers
    - huggingface-hub
    - safetensors
    - tokenizers
    - regex
    - requests
    - pillow
    - typing-extensions
    - filelock
    - fsspec
    - packaging
    - pyyaml
    - numba
    - pynndescent
    - contourpy
    - cycler
    - fonttools
    - kiwisolver
    - pyparsing
    - python-dateutil
    - joblib
    - threadpoolctl
    - jinja2
    - markupsafe
    - charset-normalizer
    - idna
    - urllib3
    - certifi
    - llvmlite
    - six
    - colorama