name: blog-recommender-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # --- Conda Packages ---
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - wordcloud
  - jupyter
  - nltk
  - pytorch
  - cpuonly
  - sentence-transformers
  - implicit
  - umap-learn
  - black
  - isort
  - flake8
  - pytest
  - pip
  - h5py
  - scikit-surprise

  # --- Pip Packages ---
  - pip:
    - annoy